substitutions:
  device_name: onkyo-tx-sr608
  friendly_name: Onkyo TX-SR608

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: nodemcuv2

# UART0 wird für den Onkyo verwendet.
# Deshalb keine serielle Logausgabe auf GPIO1/GPIO3.
logger:
  baud_rate: 0
  level: DEBUG

api:
  encryption:
    key: !secret onkyo_api_key

ota:
  - platform: esphome
    encryption:

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_password_iot

  ap:
    ssid: "Onkyo Fallback"
    password: !secret fallback_password

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/domhit/esphome-onkyo-iscp
      ref: dev/v0.6.0
    components:
      - onkyo_iscp
    refresh: 0s

uart:
  id: onkyo_uart
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 512

onkyo_iscp:
  id: onkyo_receiver
  uart_id: onkyo_uart
  update_interval: 30s

binary_sensor:
  - platform: onkyo_iscp
    onkyo_iscp_id: onkyo_receiver
    connected:
      name: Receiver verbunden

switch:
  - platform: onkyo_iscp
    onkyo_iscp_id: onkyo_receiver

    power:
      name: Power
      icon: mdi:power

    mute:
      name: Mute
      icon: mdi:volume-mute

    audyssey:
      name: Audyssey

    dynamic_eq:
      name: Dynamic EQ

    re_eq:
      name: Re-EQ

    music_optimizer:
      name: Music Optimizer

number:
  - platform: onkyo_iscp
    onkyo_iscp_id: onkyo_receiver

    master_volume:
      name: Master-Lautstärke absolut
      mode: slider

    master_volume_relative:
      name: Master-Lautstärke relativ
      mode: slider
      
    front_bass:
      name: Bass Front
      mode: slider

    front_treble:
      name: Treble Front
      mode: slider

    subwoofer_level:
      name: Subwoofer-Level
      mode: slider

    center_level:
      name: Center-Level
      mode: slider

    sleep_timer:
      name: Sleep-Timer
      mode: box

    fm_frequency:
      name: FM-Frequenz
      mode: box

    am_frequency:
      name: AM-Frequenz
      mode: box

    tuner_preset:
      name: Tuner-Preset
      mode: box

select:
  - platform: onkyo_iscp
    onkyo_iscp_id: onkyo_receiver

    input:
      name: Eingang
      sources:
        - onkyo_name: "VCR/DVR"
          name: "XBOX"
    
        - onkyo_name: "CBL/SAT"
          name: "PS4"
    
        - onkyo_name: "GAME/TV"
          name: "PS3"
    
        - onkyo_name: "AUX1"
          name: "Switch"
    
        - onkyo_name: "PC"
          name: "Wii"
    
        - onkyo_name: "BD/DVD"
          name: "PS2"
    
        - onkyo_name: "TV/CD"
          name: "XBOX360"
    
        - onkyo_name: "FM"
          name: "FM"
    
        - onkyo_name: "AM"
          name: "AM"
    
        - onkyo_name: "TUNER"
          name: "Tuner"
    
        - onkyo_name: "UNIVERSAL PORT"
          name: "Universal Port"
          
    listening_mode:
      name: Listening Mode

    dynamic_volume:
      name: Dynamic Volume

    late_night:
      name: Late Night
    
    dimmer:
      name: Displayhelligkeit

    audio_selector:
      name: Audio Selector

    speaker_layout:
      name: Speaker Layout
      disabled_by_default: true

    pty:
      name: RDS Programmtyp

    hdmi_audio_out:
      name: HDMI Audio Out
      disabled_by_default: true

    monitor_resolution:
      name: Monitor-Auflösung
      disabled_by_default: true

    video_wide_mode:
      name: Video Wide Mode
      disabled_by_default: true

    picture_mode:
      name: Picture Mode
      disabled_by_default: true
    
    display_mode:
      name: Displaymodus
      
button:
  - platform: onkyo_iscp
    onkyo_iscp_id: onkyo_receiver

    volume_up:
      name: Lauter

    volume_down:
      name: Leiser

    query_all:
      name: Status vollständig abfragen

    preset_up:
      name: Preset vor

    preset_down:
      name: Preset zurück

    preset_store:
      name: Aktuellen Sender speichern
      
    rds_radio_text:
      name: RDS Radio Text anzeigen

    rds_pty:
      name: RDS PTY anzeigen

    rds_tp:
      name: RDS TP anzeigen

    rds_next:
      name: RDS-Anzeige weiterschalten

    pty_scan:
      name: PTY-Suche starten

    tp_scan:
      name: TP-Suche starten

    osd_menu:
      name: Setup-Menü
      disabled_by_default: true

    osd_up:
      name: OSD Hoch
      disabled_by_default: true

    osd_down:
      name: OSD Runter
      disabled_by_default: true

    osd_left:
      name: OSD Links
      disabled_by_default: true

    osd_right:
      name: OSD Rechts
      disabled_by_default: true

    osd_enter:
      name: OSD Bestätigen
      disabled_by_default: true

    osd_exit:
      name: OSD Beenden
      disabled_by_default: true

    osd_home:
      name: OSD Home
      disabled_by_default: true

    osd_quick:
      name: Quick Setup
      disabled_by_default: true

    osd_audio:
      name: Audio-Menü
      disabled_by_default: true

    osd_video:
      name: Video-Menü
      disabled_by_default: true
      
    display_audio_format:
      name: Audioformat anzeigen

    display_video_format:
      name: Videoformat anzeigen

    display_mode_next:
      name: Displaymodus weiterschalten

    speaker_level_test:
      name: Lautsprecher-Testton
      disabled_by_default: true

    speaker_level_next:
      name: Nächster Lautsprecher
      disabled_by_default: true

    speaker_level_up:
      name: Lautsprecherpegel erhöhen
      disabled_by_default: true

    speaker_level_down:
      name: Lautsprecherpegel verringern
      disabled_by_default: true
      
text_sensor:
  - platform: onkyo_iscp
    onkyo_iscp_id: onkyo_receiver

    audio_information:
      name: Audio-Signalinformation

    video_information:
      name: Video-Signalinformation   
      
    last_frame:
      name: Letzter ISCP-Frame
    
    last_unknown_frame:
      name: Letzter unbekannter ISCP-Frame
      
    display:
      name: Display
      disabled_by_default: true

    audio_input_format:
      name: Audio-Eingangsformat

    audio_sample_rate:
      name: Audio-Abtastrate

    audio_input_channels:
      name: Audio-Eingangskanäle

    audio_output_channels:
      name: Audio-Ausgangskanäle

    video_input:
      name: Video-Eingang

    video_input_resolution:
      name: Video-Eingangsauflösung

    video_output:
      name: Video-Ausgang

    video_output_resolution:
      name: Video-Ausgangsauflösung